[package]
name = "rust_vec"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "An independent implementation of Rust's growable array (Vec) type."


[dependencies]
